// compilation of all libraries

#pragma once

#include "button.hpp"
#include "circle.hpp"
#include "cli.hpp"
#include "containerControl.hpp"
#include "control.hpp"
#include "cuit.hpp"
#include "global.hpp"
#include "hsl.hpp"
#include "hsv.hpp"
#include "label.hpp"
#include "panel.hpp"
#include "pos.hpp"
#include "pseudoGraphics.hpp"
#include "rect.hpp"
#include "seqColor.hpp"
#include "rgb.hpp"
#include "scrollableControl.hpp"
#include "shape.hpp"
#include "square.hpp"
#include "sz.hpp"
#include "utils.hpp"
#include "window.hpp"
#include "windowSettings.hpp"
#include "debug.hpp"